
MODULE conduct_common
  IMPLICIT NONE
  INTEGER, PARAMETER :: NI = 52, NJ = 52, NFMAX = 10, NZMAX = 10
  
  
  ! Parámetros
  

  ! Variables compartidas
  CHARACTER(LEN=18) :: TITLE(NFMAX)
  CHARACTER(LEN=18) :: VTKTITLE(NFMAX)
  CHARACTER(LEN=64) :: HEADER, PRINTF, PLOTF
  REAL, TARGET, DIMENSION(NI,NJ,NFMAX) :: F

  REAL :: ALAM(NI,NJ), GAM(NI,NJ)
  REAL, POINTER :: SC(:,:), SP(:,:)
  REAL, TARGET :: CON(NI,NJ), AP(NI,NJ)
  REAL :: AIP(NI,NJ), AIM(NI,NJ), AJP(NI,NJ), AJM(NI,NJ)
  INTEGER :: IBLOCK(NI,NJ)
  REAL :: X(NI), XU(NI), XCV(NI), ARX(NJ), Y(NJ), YV(NJ), YCV(NJ)
  REAL :: YCVR(NJ), R(NJ), RV(NJ), SX(NJ)
  REAL :: PTX(NI), QTX(NI), PTY(NJ), QTY(NJ)
  REAL :: FLUXI1(NJ,NFMAX), FLUXL1(NJ,NFMAX), FLUXJ1(NI,NFMAX)
  REAL :: FLUXM1(NI,NFMAX)
  INTEGER :: KBCI1(NJ), KBCL1(NJ), KBCJ1(NI), KBCM1(NI)
  REAL :: FLXCI1(NJ), FLXCL1(NJ), FLXCJ1(NI), FLXCM1(NI)
  REAL :: FLXPI1(NJ), FLXPL1(NJ), FLXPJ1(NI), FLXPM1(NI)

  ! COMMON /GENL/
  INTEGER :: NF, L1, L2, L3, M1, M2, M3, ITER
  REAL :: SMALL, BIG, TIME, DT
  INTEGER :: LAST, MODE, KORD, KOUT, IU1, IU2, KPGR, KSTOP

  ! COMMON /NFF/
  REAL :: RELAX(NFMAX), CRIT(NFMAX)
  INTEGER :: KPRINT(NFMAX), KSOLVE(NFMAX), KBLOC(NFMAX)
  INTEGER :: KPLOT(NFMAX), NTIMES(NFMAX), NTC(NFMAX)

  ! COMMON /EZG/
  INTEGER :: NCVLX, NCVLY
  REAL :: XL, YL

  ! COMMON /ZON/
  INTEGER :: NZX, NZY, NCVX(NZMAX), NCVY(NZMAX)
  REAL :: POWRX(NZMAX), POWRY(NZMAX)
  REAL :: XZONE(NZMAX), YZONE(NZMAX)
  REAL :: POWERX, POWERY
  SAVE
  CONTAINS
    SUBROUTINE EQUIVAL()
      SC => CON
      SP => AP
    END SUBROUTINE
END MODULE conduct_common
